### PR TITLE
Wait after writing so userland gets expected speed

### PR DESCRIPTION
**Pull request by colinleroy**
Constrain tty0tty's bandwidth by waiting the required amount of time after writing bytes, so that userland can expect write/read speeds consistent with the current baud rate, data bits, parity and stop bits settings.

### CODE REVIEW

**Comment by colinleroy** [comment]
Hi again @stappersg,

I hope that's more in line with what you expected :-) I split commits so they each do one single thing.

**Comment by stappersg** [comment]
For the record:  To avoid that github.com would squash the commits, I have them applied outside github.com. 
```text
git remote add colinleroy https://github.com/colinleroy/tty0tty.git
git fetch colinleroy
git switch respect-serial-speed 
git rebase master
git format-patch master
less 0001-Replace-debug-ifdefs-printks-with-a-macro.patch 
less 0002-Count-total-bits-per-byte.patch 
# reviewed the other commits
git switch -  # back at master branch
git merge respect-serial-speed 
git log   # verified that it are separate commits
git push
```

After that I clicked on the `merge button` in github.com webinterface, which resulted in unwanted commit message from github.com.

**Comment by colinleroy** [comment]
Hi,

> After that I clicked on the `merge button` in github.com webinterface, which resulted in unwanted commit message from github.com.

Yeah, it does that even if the code is already in :-(
The CURL dev does the same as you, merge outside of github, and after that he clicks Close on the PR instead of Merge.

**Comment by colinleroy** [comment]
Thanks for merging anyway ! :)

**Comment by stappersg** [comment]
On Sun, Sep 15, 2024 at 09:15:47AM -0700, Colin Leroy-Mira wrote:
> On Sun, Sep 15, 2024 stappers wrote:
> > After that I clicked on the `merge button` in github.com webinterface,
> > which resulted in unwanted commit message from github.com.
> 
> Yeah, it does that even if the code is already in :-(
> The CURL dev does the same as you, merge outside of github,
> and after that he clicks Close on the PR instead of Merge.

Thanks for sharing.

I shall raise it in an issue.


Groeten
Geert Stappers
-- 
Silence is hard to parse

**Pull request merged**
