### PR TITLE
Return 0 space instead of -EINVAL when there are no readers

### PR DESCRIPTION
**Pull request by klogg**
Actually no errors are suppressed here. Returning 0 is more correct in this case because -EINVAL would mean there is some invalid value passed on write, which is not true - write request itself is totally fine; returning 0 means no data was successfully written, which is true because there is no reader to consume.

NOTE: this is a split of #26

### CODE REVIEW

**Comment by stappersg** [comment]
We are getting closer.

_to be continued_

**Comment by klogg** [comment]
> We are getting closer.
> _to be continued_

Didn't get this comment.

**Comment by stappersg** [comment]
#30 and #31 do obsolete this pull request.

**Comment by klogg** [comment]
> #30 and #31 do obsolete this pull request.

Disagree. You are still returning error which is incorrect in case of 'write'

**Comment by daniel-starke** [comment]
`-ENODEV` is also not allowed here. See https://github.com/torvalds/linux/commit/6bfbfcfc58005ee12d37b56a5e722618ef6bee8f

**Comment by klogg** [comment]
Rebased to master.
@jbuchbinder this patch still valid.
@stappersg please see [comment](https://github.com/freemed/tty0tty/pull/28/#issuecomment-882118761) from @daniel-starke - changes introduced in #30 and #31 are incorrect from the Linux kernel POV.

**Comment by stappersg** [comment]
The https://github.com/torvalds/linux/commit/6bfbfcfc58005ee12d37b56a5e722618ef6bee8f  is https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6bfbfcfc58005ee12d37b56a5e722618ef6bee8f and says
> The tty line disciplines don't expect tty_operations::write_room to return negative values.

Then seeing  distinct return values, `ENODEV` and `EINVAL`, all being replaced by the same `0` feels wrong.

The 
> make everyone's write_room return >= 0

also expressed as _tty line disciplines don't expect **negative** values_  would allow other values as just `0`.


Anyway:
* Comment has been seen
* Further research is needed before _nullification_ of an error code
* That research isn't scheduled in a near future

**Comment by klogg** [comment]
Well, I do not think you need any research here, just following best practice. It is pretty obvious that kernel drivers express different behavior here, as shown above. Moreover, any existing tty tool will break with negative on write - you can check yourself e.g. with socat.

**Comment by jbuchbinder** [comment]
Merging to un-break the current behavior with other tools. If we're going to change the return values to be distinct for specific breaking error conditions, that's fine, we can change them to be positive return values. 0 for now, additional patches welcome.

**Pull request merged**
