### PR TITLE
use <term.h> instead of <termio.h> on macos

### PR DESCRIPTION
**Pull request by fairfieldt**

### CODE REVIEW

**Comment by stappersg** [comment]
@fairfieldt  Why?

**Comment by fairfieldt** [comment]
> 
> 
> @fairfieldt Why?

termio.h does not exist on macos

**Comment by stappersg** [comment]
Acknowledge.

Thing I would like to see is that the commit message besides the
```
use <term.h> instead of <termio.h> on macos
```
also states
```
so this Linux kernel module can also be used on macos
```

**Comment by fairfieldt** [comment]
> 
> 
> Acknowledge.
> 
> Thing I would like to see is that the commit message besides the
> 
> ```
> use <term.h> instead of <termio.h> on macos
> ```
> 
> also states
> 
> ```
> so this Linux kernel module can also be used on macos
> ```

The kernel module won't work - this only changes pts/tty0tty to work on macos.

**Comment by stappersg** [comment]
> this only changes pts/tty0tty to work on macos

Ah, now I see `pts/`.   The file path was there all the time.

**Review by stappersg — APPROVED** [review]
LGTM

**Comment by stappersg** [comment]
Hello human,

Thanks for having a look at this open pull request.
Please look also at the date of when the PR was created.

Now please transform the _disappointment_ in something useful. Like that you learnt that you are not here for the website but for meeting people. That we can make the world a better place by talking to each other, that we, people, did give away too much to github.com.  Go find the universe outside the github world.

**Review by jbuchbinder — APPROVED** [review]

**Pull request merged**
